<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="70458" started-at="2018-02-28T07:22:47Z" finished-at="2018-02-28T07:23:58Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="70458" started-at="2018-02-28T07:22:47Z" finished-at="2018-02-28T07:23:58Z">
      <class name="TestCases.LoginPageTest">
        <test-method status="PASS" signature="init()[pri:0, instance:TestCases.LoginPageTest@3ffc5af1]" name="init" is-config="true" duration-ms="8750" started-at="2018-02-28T12:53:32Z" finished-at="2018-02-28T12:53:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="verifyLogin()[pri:0, instance:TestCases.LoginPageTest@3ffc5af1]" name="verifyLogin" duration-ms="16638" started-at="2018-02-28T12:53:41Z" finished-at="2018-02-28T12:53:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
      </class> <!-- TestCases.LoginPageTest -->
      <class name="TestCases.TestCase1">
        <test-method status="PASS" signature="init()[pri:0, instance:TestCases.TestCase1@29774679]" name="init" is-config="true" duration-ms="24059" started-at="2018-02-28T12:52:48Z" finished-at="2018-02-28T12:53:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="test1()[pri:0, instance:TestCases.TestCase1@29774679]" name="test1" duration-ms="16" started-at="2018-02-28T12:53:12Z" finished-at="2018-02-28T12:53:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="quit()[pri:0, instance:TestCases.TestCase1@29774679]" name="quit" is-config="true" duration-ms="446" started-at="2018-02-28T12:53:12Z" finished-at="2018-02-28T12:53:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="PASS" signature="init()[pri:0, instance:TestCases.TestCase1@29774679]" name="init" is-config="true" duration-ms="17560" started-at="2018-02-28T12:53:12Z" finished-at="2018-02-28T12:53:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="test2()[pri:0, instance:TestCases.TestCase1@29774679]" name="test2" duration-ms="5" started-at="2018-02-28T12:53:30Z" finished-at="2018-02-28T12:53:30Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at TestCases.TestCase1.test2(TestCase1.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="quit()[pri:0, instance:TestCases.TestCase1@29774679]" name="quit" is-config="true" duration-ms="2086" started-at="2018-02-28T12:53:30Z" finished-at="2018-02-28T12:53:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- TestCases.TestCase1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
